version: '3.3'
services: 
        web: 
         build:
             context: ./Login
             dockerfile: Dockerfile
         container_name: php74
         depends_on:
              - db
         volumes:
            - ./Login:/var/www/html/
         ports:
            - "8004:80"
        db: 
         container_name: mysqldat
         image: jonishsolanki199/userdata
         command: --default-authentication-plugin=mysql_native_password
         restart: always
         environment: 
               MYSQL_ROOT_PASSWORD: root 
               MYSQL_DATABASE: user
               MYSQL_USER: jonish
               MYSQL_PASSWORD: jonish
         ports: 
             - "3305:3306"
